scrape_configs:
  - job_name: 'postgres'
    scrape_interval: 10s
    static_configs:
      - targets: ['postgres_exporter:9187']
  - job_name: 'pgbouncer'
    scrape_interval: 10s
    static_configs:
    - targets: ['pgbouncer_exporter:9127']